INSERT INTO CONFERENCE(title,start,finish) VALUES ('KONFERENCJA NR 1','2021-06-01 10:00:00','2021-06-01 11:45:00');
INSERT INTO CONFERENCE(title,start,finish) VALUES ('KONFERENCJA NR 2','2021-06-01 12:00:00','2021-06-01 13:45:00');
INSERT INTO CONFERENCE(title,start,finish) VALUES ('KONFERENCJA NR 3','2021-06-01 14:00:00','2021-06-01 15:45:00');

-- TEMATYKI SPOTKAN
INSERT INTO TOPIC (title) VALUES ('JAVA');
INSERT INTO TOPIC (title) VALUES ('PHP');
INSERT INTO TOPIC (title) VALUES ('JS');
INSERT INTO TOPIC (title) VALUES ('CSS');

-- PRZYPISANIE TEMATKI DO SPOTKANIA
INSERT INTO THEME_CONFERENCE(conference_id,topic_id)VALUES(1,3),(1,4),(1,2);
INSERT INTO THEME_CONFERENCE(conference_id,topic_id)VALUES(2,1),(2,2),(2,3);
INSERT INTO THEME_CONFERENCE(conference_id,topic_id)VALUES(3,1),(3,2),(3,3);

-- DODANIE UCZESTNIKOW KONFERENCJI
INSERT INTO PARTICIPANT(login,email)VALUES('test_login1','test1@mail.com');
INSERT INTO PARTICIPANT(login,email)VALUES('test_login2','test2@mail.com');
INSERT INTO PARTICIPANT(login,email)VALUES('test_login3','test3@mail.com');
INSERT INTO PARTICIPANT(login,email)VALUES('test_login4','test4@mail.com');
INSERT INTO PARTICIPANT(login,email)VALUES('test_login5','test5@mail.com');
INSERT INTO PARTICIPANT(login,email)VALUES('test_login6','test6@mail.com');

-- DODANIE UCZESNIKOW DO SPOTKANIA
INSERT INTO CONFERENCE_PARTICIPANTS(theme_conference_id,participant_id) VALUES (1,1);
INSERT INTO CONFERENCE_PARTICIPANTS(theme_conference_id,participant_id) VALUES (1,2);
INSERT INTO CONFERENCE_PARTICIPANTS(theme_conference_id,participant_id) VALUES (1,3);
INSERT INTO CONFERENCE_PARTICIPANTS(theme_conference_id,participant_id) VALUES (1,4);