CREATE TABLE CONFERENCE (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    start TIMESTAMP NOT NULL,
    finish TIMESTAMP NOT NULL
);

CREATE TABLE TOPIC (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL
);

CREATE TABLE CONFERENCE_TOPICS(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    conference_id BIGINT,
    topic_id BIGINT,

    CONSTRAINT FK_conference FOREIGN KEY (conference_id) REFERENCES CONFERENCE (id),
    CONSTRAINT FK_topic FOREIGN KEY (topic_id) REFERENCES TOPIC (id)
);

